apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaos-button.fullname" . }}-frontend
  labels:
    {{- include "chaos-button.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "chaos-button.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontendPort }}
      targetPort: http
