apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chaos-button.fullname" . }}-frontend
  labels:
    {{- include "chaos-button.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chaos-button.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chaos-button.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 2
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
