{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chaos-button.fullname" . }}
  labels:
    {{- include "chaos-button.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "chaos-button.fullname" . }}-backend
                port:
                  number: {{ .Values.service.backendPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chaos-button.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontendPort }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
